[package]
name = "YYScreenTime_win-rs"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/yy-tromb/YYScreenTime_win-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.82", features = ["backtrace"] }
iced = "0.12.1"
tokio = "1.37.0"

[dependencies.windows]
version = "0.56.0"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Threading",
    "Win32_Storage_FileSystem",
    "Win32_System_ApplicationInstallationAndServicing",
]
